patient.msg =Welcome to the bankapplication Cards Prod application
patient.build-version=1

patient.mailDetails.hostName=prod-cards@jcb826.com
patient.mailDetails.port=9012
patient.mailDetails.from=prod-cards@jcb826.com
patient.mailDetails.subject=Your Card Details from bankapplication Production Environment

patient.activeBranches[0]=Hyderabad
patient.activeBranches[1]=Paris
patient.activeBranches[2]=NewYork
